### ISSUE TITLE
missing info about JSON.

### ISSUE THREAD

**Issue by olegharput** [wlbr/cl-marshal#16]
I am trying to use cl-marshal for json something like
`(ms:marshal (list '{
				    "aa" :    20
				 '}))`
but it gives error:
"illegal terminating character after a colon: #\

  Line: 2, Column: 14, File-Position: 34

  Stream: #<SB-IMPL::STRING-INPUT-STREAM {10015C2E93}>
   [Condition of type SB-INT:SIMPLE-READER-ERROR]"

is there a way to solve it?

**Comment by wlbr** [comment]
This is not a problem of cl-marshal - `(list '{ "aa" :    20 '})` is not a valid lisp expression. You cannot evaluate it, you will get reader errors. The `'` is not the lisp way to create a character. `(list #\{ "aa" #\: 20 #\})` would be valid somehow - but probably useless.

If you try to read and create JSON from Common Lisp you should take a look at the libraries listed here: [https://www.cliki.net/JSON](https://www.cliki.net/JSON)
