### ISSUE TITLE
Global `FMT` nickname is problematic

### ISSUE THREAD

**Issue by vindarel** [wlbr/cl-marshal#18]
Hello there,

in package.lisp we see a global nickname:

```lisp
(defpackage :serialization-format
  (:use :cl)
  (:nicknames :fmt)
```

but this can now lead to an error because `fmt` is now a proper system distributed by Quicklisp.

I tried to quickload CheckL, relying on cl-marshal, and couldn't (https://github.com/rpav/CheckL/issues/6).

The solution would be to use a package-local nickname, or another nickname, or no nickname. 

Best,

**Comment by cage2** [comment]
Hi @vindarel !

I just pushed a fix using local nicknames as you suggested; just to be sure please can you test building CheckL with this version of cl-marshal?

Bye!
C.

**Comment by vindarel** [comment]
Hi Cage, it works fine thank you very much!

**Comment by cage2** [comment]
> Hi Cage,

Hi!

> it works fine thank you very much!

Thanks to you for reporting the issue!

Bye!
C.
