### ISSUE TITLE
MARSHAL fails to correctly handle some strings.

### ISSUE THREAD

**Issue by thomp** [wlbr/cl-marshal#2]
MARSHAL handles simple strings fine but becomes distressed with some other strings.

    TT> (defparameter *our-string* 
          (make-array 20 :adjustable t :fill-pointer 0 :element-type 'character))
    *OUR-STRING*
    TT> (vector-push-extend #\x *our-string*)
    0
    TT> *our-string*
    "x"
    TT> (ms:marshal *our-string*)
    (:PCODE 1 (:STRING 1 1 T ""))
    TT> (ms:unmarshal (ms:marshal *our-string*))
    ; Evaluation aborted on #<SIMPLE-ERROR "invalid fill-pointer ~W" {C5EC4D1}>.

**Comment by wlbr** [comment]
Hi, I cannot reproduce the error. Which environment do you use?

My results on ClozureCL 1.10-r16196:

```lisp
(defparameter *our-string* 
      (make-array 20 :adjustable t :fill-pointer 0 :element-type 'character))
;--> *OUR-STRING*
```

```lisp
(describe *our-string*)
; -->
;Type: (BASE-STRING 20)
;Class: #<BUILT-IN-CLASS BASE-STRING>
;Adjustable, Element type: CHARACTER
;Fill Pointer: 0
;Physical size: 20
;Data vector: ""
;Displacement: 0
;Flags: #xC9C0
```

```lisp
(ms:marshal *our-string*)
;--> (:PCODE 1 (:STRING 1 0 T ""))
```

```lisp
(ms:unmarshal (ms:marshal *our-string*))
;--> ""
```
Works for me.

**Comment by wlbr** [comment]
Sorry, got it, the I didn't see the vector-push-extend. 
Can reproduce the problem now.

**Comment by thomp** [comment]
This was with SBCL.1.0.58. I find that things work fine as well -- with an empty string...

    TT> (defparameter *our-string* 
          (make-array 20 :adjustable t :fill-pointer 0 :element-type 'character))
    *OUR-STRING*
    TT> (describe *our-string*)
    ""
      [string]
    
    Element-type: CHARACTER
    Fill-pointer: 0
    Size: 20
    Adjustable: yes
    Displaced-to: NIL
    Displaced-offset: 0
    Storage vector: "                    "
    ; No value
    TT> *our-string*
    ""
    TT> (ms:unmarshal (ms:marshal *our-string*))
    ""

Do you encounter any issues when you use a non-empty string? This is where things seem to go downhill for me...

    TT> (defparameter *our-string* 
          (make-array 20 :adjustable t :fill-pointer 0 :element-type 'character))
    *OUR-STRING*
    TT> (describe *our-string*)
    ""
      [string]
    
    Element-type: CHARACTER
    Fill-pointer: 0
    Size: 20
    Adjustable: yes
    Displaced-to: NIL
    Displaced-offset: 0
    Storage vector: "                    "
    ; No value
    TT> (vector-push-extend #\x *our-string*)
    0
    TT> *our-string*
    "x"
    TT> (ms:unmarshal (ms:marshal *our-string*))
    ; Evaluation aborted on #<SIMPLE-ERROR "invalid fill-pointer ~W" {C6FCA41}>.

**Comment by thomp** [comment]
Oops... didn't catch your comment -- should have refreshed the page before sending the above.

**Comment by wlbr** [comment]
Please check the new version (git clone, not quickload). Works with my tests now.

All elements of the array get mashalled now, even thos behind the fill-pointer. I think this is more than questionable, probably those "dead" elements should be skipped and only those until the fill-pointer should be marshalled.

**Comment by thomp** [comment]
1. Thanks -- works for me. 

2. Marshalling all elements seems the most conservative approach -- should it prove excessive, it would make sense to consider the approach you suggest (ignoring the 'dead' elements).
