### ISSUE TITLE
Does not serialize circular list

### ISSUE THREAD

**Issue by TeMPOraL** [wlbr/cl-marshal#3]
The README says it works with circles. Unless I misunderstood it, this should work:

``` lisp
 (let ((a (list 1 2 3)))
   (setf (cdddr a) a)
   (let ((*print-circle* t))
     (marshal:marshal a)))
```

It does not work (i.e. locks up in an infinite loop) on my configuration though.
SBCL 1.2.9 X86-64

Not that I need this very much, it's just a first thing I tested after serializing some other objects ;).

**Comment by cage2** [comment]
Hello!

I think the commit: 
https://github.com/wlbr/cl-marshal/commit/cf263276ff4488fc1daa294e0bb319b3352e6dc2
resolve this issue and some other backreferences problem in list. Now it (de)serialize lists like:

```
'#1=(2 2 #2=(a b) (#1# #1# (#1# #2#)) 5 #2# c . #1#)
```

However this is more an hack than a general solution, but i think could be considered good enough. If not feel free to reopen the issue.

Bye!
C.
