### ISSUE TITLE
s/persistant/persistent/

### ISSUE THREAD

**Issue by TeMPOraL** [wlbr/cl-marshal#4]
A misspeling in things like `class-persistant-slots`. Changing it now would probably break some code, but I'd personally appreciate at least an alias with correct spelling for pedantic reasons ;).

**Comment by cage2** [comment]
Hopefully, revision https://github.com/wlbr/cl-marshal/commit/bc23d760a071bdf56cc0fbaebfc57cd0263e0896, solve this issue.

**Comment by wlbr** [comment]
Thanks again!
I guess it was my best idea since a long time, to ask you to takover a
collaborator role!

;-)
Michael


2017-01-13 15:35 GMT+01:00 cage2 <notifications@github.com>:

**Comment by cage2** [comment]
On Fri, Jan 13, 2017 at 06:37:35AM -0800, Michael Wolber wrote:
> Thanks again!
> I guess it was my best idea since a long time, to ask you to takover a
> collaborator role!
>
> ;-)
> Michael

Thank you for your kind words!

Happy to be useful and, moreover, working with this library is fun! :)

Bye!
C.
