### ISSUE TITLE
Can't serialize a CONS

### ISSUE THREAD

**Issue by chebert** [wlbr/cl-marshal#5]
```
(marshal:marshal (cons 3 4))
```

Signals an error that 4 isn't a list.

SBCL: 1.2.6
cl-marshal-20150302-git
quicklisp 2015-04-07

**Comment by wlbr** [comment]
It seems that quicklisp is not using the latest version of cl-marshal. If I use the trunk, then I cannot reproduce the error. I seem to have fixed the error some years ago.

I'll try to find out how to update the quicklisp distro.

**Comment by wlbr** [comment]
Fixed with 2624335faff01a68611c07627b4b663bec82a711
Cudos to 'cage2' for the fix.
