### ISSUE TITLE
Specify a package for unmarshalled classes

### ISSUE THREAD

**Issue by vityok** [wlbr/cl-marshal#8]
Make it possible to specify a package where to look for classes during unmarshalling. At the moment classes are marshalled without preserving their package names. During deserialization/unmarshalling the code fails to find corresponding symbols.

A possible solution is either to store the package name along with the class name during marshalling and another is to make it possible to specify the desired package name for symbols during unmarshalling. Then the unmarshal-fn code might look something like:

```lisp
(defparameter *ms-symbols-package* nil)

;;;  07.07.98 cjo: LOOP
(defmethod unmarshal-fn ((version (eql (coding-idiom :coding-release-no)))
                      (type (eql (coding-idiom :object))) token &optional (circle-hash NIL))
   (let* ((class-name (find-symbol (symbol-name (third token)) *ms-symbols-package*))
          (out (make-instance class-name))
          (slots (class-persistant-slots out))
          (values (cdddr token)))
```

And a `with-ms-symbols-package` macro can be created to encapsulate the required `let`:

```lisp
(let ((ms:*ms-symbols-package* 'my-package))
  (ms:unmarshal thing))
```

**Comment by cage2** [comment]
Hello!

I prefer the first solution, but i would like to know some opinion from other people too.

Bye!
C.

**Comment by cage2** [comment]
Hello!

https://github.com/wlbr/cl-marshal/commit/9369672b6e30bf189a68c73b049fe926625c7aeb uses package name in serialized object.

Bye!
C.

**Comment by wlbr** [comment]
Sorry, currently I don’t have the time for Lisp and to dig deeper into a serious algorithm. 
Hopefully this will change later over the year.

Bye
Michael

**Comment by cage2** [comment]
On Thu, Jan 19, 2017 at 04:02:19PM -0800, Michael Wolber wrote:

Hello!

> Sorry, currently I don’t have the time for Lisp and to dig deeper into a serious algorithm.
> Hopefully this will change later over the year.

Not a problem at all! In the meanwhile all issues have been closed! :)

Bye.
C.

**Comment by wlbr** [comment]
yes, I've seen this. This is really great work, thanks a lot!!
 

Gesendet: Freitag, 20. Januar 2017 um 16:20 Uhr
Von: cage2 <notifications@github.com>
An: wlbr/cl-marshal <cl-marshal@noreply.github.com>
Cc: "Michael Wolber" <mwolber@gmx.de>, Comment <comment@noreply.github.com>
Betreff: Re: [wlbr/cl-marshal] Specify a package for unmarshalled classes (#8)

On Thu, Jan 19, 2017 at 04:02:19PM -0800, Michael Wolber wrote:

Hello!

> Sorry, currently I don’t have the time for Lisp and to dig deeper into a serious algorithm.
> Hopefully this will change later over the year.

Not a problem at all! In the meanwhile all issues have been closed! :)

Bye.
C.
